### ISSUE TITLE
Start Angular CLI & ASP.NET Core from scratch

### ISSUE THREAD

**Issue by robisim74** [robisim74/AngularCliAspNetCore#1]
- Requirements
    - At least [.NET Core 2.0](https://www.microsoft.com/net/download/core)
    - [Node.js and npm](https://docs.npmjs.com/getting-started/installing-node)
    - At least [Angular CLI 1.5.0](https://github.com/angular/angular-cli)

<br>

- Create the Angular app:
```
ng new AngularCliAspNetCore
cd AngularCliAspNetCore
```

- Create the ASP.NET Core WebAPI:
```
dotnet new webapi --use-launch-settings
```

- Open _.angular-cli.json_ file and set the _outDir_:
```
"outDir": "wwwroot"
```

- Open _Startup.cs_ file and add to the _configure_ method:
```
app.UseMvc();

// Microsoft.AspNetCore.StaticFiles: API for starting the application from wwwroot.
// Uses default files as index.html.
app.UseDefaultFiles();
// Uses static file for the current path.
app.UseStaticFiles();
```

- Create _proxy.config.json_ file, to send the requests to the backend server rather than the webpack dev-server during the development:
```
{
  "/api": {
	"target": "http://localhost:5000/",
	"secure": false
  }
}
```

- Open _package.json_ file and set the following scripts:
```
"start": "ng serve --aot --proxy-config proxy.config.json",
"build": "ng build --prod",
```

- Open _launchSettings.json_ file and set the environments: [launchSettings](https://github.com/robisim74/AngularCliAspNetCore/blob/master/Properties/launchSettings.json)

- To run automatically the _npm start_ command, you can add the [ShellExtensions](https://github.com/robisim74/AngularCliAspNetCore/blob/master/Extensions/ShellExtensions.cs) and use it in _Startup.cs_:
```
if (env.IsDevelopment())
{
    ....
    // Starts "npm start" command using Shell extension.
    app.Shell("npm start");
}
```

- Done

For other features, refer to the repository.

**Comment by rbhargaw2148** [comment]
Thanks! This was very helpful!

**Comment by robisim74** [comment]
Updated & added in the README
