### ISSUE TITLE
Wildcard routing

### ISSUE THREAD

**Issue by mattsibenaller** [robisim74/AngularCliAspNetCore#3]
With this setup how do you go about handling wildcard routing on the server?

I usually use something like this in the routing file:
  { path: '**', redirectTo: 'error' }

However, that doesn't seem to work on the server.  Do you handle it at the server level?  I'd rather handle it with Angular personally.  BTW, the project is great!  I love the idea of having my api with my Angular project.

Thanks!

**Comment by robisim74** [comment]
Why do you need to handle it at the server level?

The router on the client must match the router on the server. Just add the `error` page also in the server: https://github.com/robisim74/AngularCliAspNetCore/blob/master/Startup.cs#L38 and it should work.

**Comment by robisim74** [comment]
Sorry I did not understand the question. For _wildcard_ routing I think you need to customize the function: https://github.com/robisim74/AngularCliAspNetCore/blob/master/Startup.cs#L43-L51

**Comment by mattsibenaller** [comment]
Yeah that's where I was at when I stopped to contact you.  If I come up with a solution I'll post back but I'm uncertain if  I'll get back to this project anytime soon. Thanks for the help!

**Comment by robisim74** [comment]
I think you should authorize server-side every single file that the application loads (even the bundles), but I've never tried. If you have time to find a solution, you are welcome.

Greetings

**Comment by robisim74** [comment]
@mattsibenaller 

I solved this problem (and simplified the whole configuration) using _SpaServices_. You can see the README for the new build.
